ktor:
    application:
        modules:
            - com.mlg.ApplicationKt.module
    deployment:
        port: 8095
security:
  login: $API_LOGIN
  password: $API_PWD
db:
  mongo:
    user: $MONGO_USER
    password: $MONGO_PWD
    host: database #database for docker - 127.0.0.1 for local
    port: 27017 # 27017 for docker - 27018 for local
    database:
      name: pktouradmin
