ktor:
    application:
        modules:
            - com.mlg.ApplicationKt.module
    deployment:
        port: 8099
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
db:
  mongo:
    user: pktouradmin
    password: pwd
    host: 127.0.0.1
    port: 27018
    database:
      name: pktouradmin
